# Generated by Django 3.0.7 on 2020-06-21 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Название курса')),
                ('desc', models.TextField(null=True, verbose_name='Описание курса')),
                ('avatar', models.FileField(null=True, upload_to='uploads/', verbose_name='Картинка курса')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Не активен'), (1, 'Активен')], default=1, verbose_name='Статус курса')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Название урока')),
                ('desc', models.TextField(null=True, verbose_name='Описание урока')),
                ('avatar', models.FileField(null=True, upload_to='uploads/', verbose_name='Картинка урока')),
                ('video', models.FileField(upload_to='uploads/video/', verbose_name='Видео материаль урока')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Не активен'), (1, 'Активен')], default=1, verbose_name='Статус курса')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
