# Generated by Django 3.0.7 on 2020-06-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200622_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked',
            name='name',
            field=models.CharField(max_length=225, null=True, verbose_name='Название урока'),
        ),
    ]
