# Generated by Django 3.0.7 on 2020-06-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_liked_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='name',
        ),
    ]
