# Generated by Django 3.0.7 on 2020-06-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_course_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='created_at',
        ),
    ]
